
name: Code Quality
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flake8:
    name: Flake8

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r test-requirements.txt
    - name: Flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Git checkout"
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt
      - name: Run tests
        run:  |
          pytest --ignore tests/smoketests

  backendSmoketests:
    name: Individual Backend Smoketests
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4
      matrix:
        backend: ["flask"]

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Git checkout"
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/backend_smoketests/${{ matrix.backend }}/requirements.txt
      - name: Run tests
        run:  |
          pytest tests/backend_smoketests/${{ matrix.backend }}/test_run.py
